### ISSUE TITLE
I see no actual files-

### ISSUE THREAD

**Issue by Lukas-Batema** [DatBoyMax/Pokemon-Spark#1]
The description explicitly mentions the accessibility of a file, but it isn't in the repo. All I see is a README.md, Please fix this, and update your description, or I will report false claims to GitHub Trust and Saftey (/jk). All jokes aside, please actually add what you say is there, not clickbait people.

**Comment by DatBoyMax** [comment]
I haven't had the time. GitHub and there damn 100 file upload limit at a time is annoying.

**Comment by Lukas-Batema** [comment]
Just commit the files through VSCode?

**Comment by Lukas-Batema** [comment]
Bump
